// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoitjnuiHvZvt9DxDeUhSCr8ld9eI7BDM',
    appId: '1:307807260069:web:f66faa9c1762d7f4616c4c',
    messagingSenderId: '307807260069',
    projectId: 'climbapp-ba9bc',
    authDomain: 'climbapp-ba9bc.firebaseapp.com',
    storageBucket: 'climbapp-ba9bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCedhsEYMr5CryR2gs_WpVUyhnUODuy-io',
    appId: '1:307807260069:android:39aa6fed03172eef616c4c',
    messagingSenderId: '307807260069',
    projectId: 'climbapp-ba9bc',
    storageBucket: 'climbapp-ba9bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH4Dqpv1aFkNaav06LczuO9OkiuSCWN2Y',
    appId: '1:307807260069:ios:21800447115b14b4616c4c',
    messagingSenderId: '307807260069',
    projectId: 'climbapp-ba9bc',
    storageBucket: 'climbapp-ba9bc.appspot.com',
    iosBundleId: 'com.example.verygoodcore.climbapp',
  );
}
